/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerLoginRouteImport } from './routes/volunteer-login'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as TeamNewRouteImport } from './routes/team.new'
import { Route as TeamJoinRouteImport } from './routes/team.join'
import { Route as SubmitTeamIdRouteImport } from './routes/submit.$teamId'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as ApiDiscordCallbackRouteImport } from './routes/api.discord.callback'

const VolunteerLoginRoute = VolunteerLoginRouteImport.update({
  id: '/volunteer-login',
  path: '/volunteer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamJoinRoute = TeamJoinRouteImport.update({
  id: '/team/join',
  path: '/team/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitTeamIdRoute = SubmitTeamIdRouteImport.update({
  id: '/submit/$teamId',
  path: '/submit/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordCallbackRoute = ApiDiscordCallbackRouteImport.update({
  id: '/api/discord/callback',
  path: '/api/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/update-password': typeof UpdatePasswordRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/submit/$teamId': typeof SubmitTeamIdRoute
  '/team/join': typeof TeamJoinRoute
  '/team/new': typeof TeamNewRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/update-password': typeof UpdatePasswordRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/submit/$teamId': typeof SubmitTeamIdRoute
  '/team/join': typeof TeamJoinRoute
  '/team/new': typeof TeamNewRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/update-password': typeof UpdatePasswordRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/submit/$teamId': typeof SubmitTeamIdRoute
  '/team/join': typeof TeamJoinRoute
  '/team/new': typeof TeamNewRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/update-password'
    | '/volunteer'
    | '/volunteer-login'
    | '/certificate/$code'
    | '/submit/$teamId'
    | '/team/join'
    | '/team/new'
    | '/verify/$code'
    | '/api/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/update-password'
    | '/volunteer'
    | '/volunteer-login'
    | '/certificate/$code'
    | '/submit/$teamId'
    | '/team/join'
    | '/team/new'
    | '/verify/$code'
    | '/api/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/update-password'
    | '/volunteer'
    | '/volunteer-login'
    | '/certificate/$code'
    | '/submit/$teamId'
    | '/team/join'
    | '/team/new'
    | '/verify/$code'
    | '/api/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  VolunteerRoute: typeof VolunteerRoute
  VolunteerLoginRoute: typeof VolunteerLoginRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  SubmitTeamIdRoute: typeof SubmitTeamIdRoute
  TeamJoinRoute: typeof TeamJoinRoute
  TeamNewRoute: typeof TeamNewRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiDiscordCallbackRoute: typeof ApiDiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer-login': {
      id: '/volunteer-login'
      path: '/volunteer-login'
      fullPath: '/volunteer-login'
      preLoaderRoute: typeof VolunteerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/new': {
      id: '/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/join': {
      id: '/team/join'
      path: '/team/join'
      fullPath: '/team/join'
      preLoaderRoute: typeof TeamJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$teamId': {
      id: '/submit/$teamId'
      path: '/submit/$teamId'
      fullPath: '/submit/$teamId'
      preLoaderRoute: typeof SubmitTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/callback': {
      id: '/api/discord/callback'
      path: '/api/discord/callback'
      fullPath: '/api/discord/callback'
      preLoaderRoute: typeof ApiDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  VolunteerRoute: VolunteerRoute,
  VolunteerLoginRoute: VolunteerLoginRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  SubmitTeamIdRoute: SubmitTeamIdRoute,
  TeamJoinRoute: TeamJoinRoute,
  TeamNewRoute: TeamNewRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiDiscordCallbackRoute: ApiDiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
